version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    groups:
      go-modules:
        patterns:
          - "*"
    cooldown:
      default-days: 2
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 2
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
