version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - gocritic
    - gosec
    - govet
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: blank-imports
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
